import type { ProjectPilotExport } from '@/features/settings/data/dataTransfer.schema';
import { createDataTransferService } from '@/features/settings/services/dataTransfer.service';
import {
  createDataTransferRepository,
  type DatabaseSnapshot,
} from '@/repositories/dataTransfer.repo';
import { createTestDb, NOW, type TestDb } from './testDb';

export function createCompleteSnapshot(): DatabaseSnapshot {
  return {
    projects: [
      {
        id: 'project-real',
        name: '真实项目',
        description: '完整测试数据',
        status: 'active',
        color: '#2563EB',
        start_date: '2026-07-01',
        target_end_date: '2026-12-31',
        archived_at: null,
        is_sample: 0,
        created_at: NOW,
        updated_at: '2026-07-15T00:00:00Z',
      },
      {
        id: 'project-sample',
        name: '示例项目',
        description: '应可从导出中排除',
        status: 'on_hold',
        color: '#6366F1',
        start_date: '2026-06-01',
        target_end_date: null,
        archived_at: null,
        is_sample: 1,
        created_at: NOW,
        updated_at: NOW,
      },
    ],
    meetings: [
      {
        id: 'meeting-project',
        project_id: 'project-real',
        topic: '项目周会',
        date: '2026-07-16',
        start_time: '09:30',
        attendees: '["Racliu","项目成员"]',
        agenda: '检查进展',
        notes: '会议纪要',
        decisions: '按计划推进',
        risks: '关注延期',
        source_rule_id: 'rule-real-meeting',
        source_occurrence_date: '2026-07-16',
        is_sample: 0,
        created_at: NOW,
        updated_at: NOW,
      },
      {
        id: 'meeting-independent',
        project_id: null,
        topic: '示例独立会议',
        date: '2026-07-17',
        start_time: null,
        attendees: '[]',
        agenda: '',
        notes: '',
        decisions: '',
        risks: '',
        source_rule_id: null,
        source_occurrence_date: null,
        is_sample: 1,
        created_at: NOW,
        updated_at: NOW,
      },
    ],
    tasks: [
      {
        id: 'task-root',
        project_id: 'project-real',
        parent_task_id: null,
        title: '父任务',
        description: '根任务',
        status: 'in_progress',
        priority: 'high',
        start_date: '2026-07-01',
        due_date: '2026-07-20',
        progress: 50,
        estimated_hours: 8,
        actual_hours: 4,
        completed_at: null,
        archived_at: null,
        source_meeting_id: 'meeting-project',
        source_rule_id: null,
        source_occurrence_date: null,
        is_sample: 0,
        created_at: NOW,
        updated_at: NOW,
      },
      {
        id: 'task-child',
        project_id: 'project-real',
        parent_task_id: 'task-root',
        title: '子任务',
        description: '第二层任务',
        status: 'todo',
        priority: 'medium',
        start_date: null,
        due_date: '2026-07-19',
        progress: 0,
        estimated_hours: null,
        actual_hours: null,
        completed_at: null,
        archived_at: null,
        source_meeting_id: null,
        source_rule_id: null,
        source_occurrence_date: null,
        is_sample: 0,
        created_at: NOW,
        updated_at: NOW,
      },
      {
        id: 'task-converted',
        project_id: 'project-real',
        parent_task_id: null,
        title: '行动项转任务',
        description: '',
        status: 'done',
        priority: 'urgent',
        start_date: '2026-07-02',
        due_date: '2026-07-18',
        progress: 100,
        estimated_hours: 2,
        actual_hours: 3,
        completed_at: '2026-07-18T08:00:00Z',
        archived_at: null,
        source_meeting_id: 'meeting-project',
        source_rule_id: 'rule-real-task',
        source_occurrence_date: '2026-07-18',
        is_sample: 0,
        created_at: NOW,
        updated_at: '2026-07-18T08:00:00Z',
      },
      {
        id: 'task-sample',
        project_id: 'project-sample',
        parent_task_id: null,
        title: '示例任务',
        description: '',
        status: 'blocked',
        priority: 'low',
        start_date: null,
        due_date: null,
        progress: 10,
        estimated_hours: null,
        actual_hours: null,
        completed_at: null,
        archived_at: null,
        source_meeting_id: null,
        source_rule_id: null,
        source_occurrence_date: null,
        is_sample: 1,
        created_at: NOW,
        updated_at: NOW,
      },
    ],
    taskDependencies: [
      {
        id: 'dependency-first',
        predecessor_id: 'task-root',
        successor_id: 'task-child',
        dep_type: 'FS',
        lag_days: 0,
        created_at: NOW,
        updated_at: NOW,
      },
      {
        id: 'dependency-second',
        predecessor_id: 'task-child',
        successor_id: 'task-converted',
        dep_type: 'FS',
        lag_days: 1,
        created_at: NOW,
        updated_at: NOW,
      },
    ],
    recurrenceRules: [
      {
        id: 'rule-real-task',
        project_id: 'project-real',
        kind: 'task',
        title: '每周复盘任务',
        byweekday: 4,
        interval: 1,
        start_date: '2026-07-04',
        end_date: '2026-12-31',
        time_of_day: null,
        duration_minutes: null,
        default_priority: 'high',
        note: '按模板复盘',
        is_active: 1,
        is_sample: 0,
        created_at: NOW,
        updated_at: NOW,
      },
      {
        id: 'rule-real-meeting',
        project_id: 'project-real',
        kind: 'meeting',
        title: '每周项目会',
        byweekday: 2,
        interval: 1,
        start_date: '2026-07-01',
        end_date: null,
        time_of_day: '09:30',
        duration_minutes: 60,
        default_priority: null,
        note: '固定议程',
        is_active: 1,
        is_sample: 0,
        created_at: NOW,
        updated_at: NOW,
      },
      {
        id: 'rule-sample-meeting',
        project_id: 'project-sample',
        kind: 'meeting',
        title: '示例例会',
        byweekday: 0,
        interval: 2,
        start_date: '2026-06-01',
        end_date: null,
        time_of_day: null,
        duration_minutes: null,
        default_priority: null,
        note: '',
        is_active: 1,
        is_sample: 1,
        created_at: NOW,
        updated_at: NOW,
      },
    ],
    recurrenceExceptions: [
      {
        id: 'exception-real-task-materialized',
        rule_id: 'rule-real-task',
        occurrence_date: '2026-07-18',
        action: 'materialized',
        replacement_date: null,
        materialized_id: 'task-converted',
        created_at: NOW,
        updated_at: NOW,
      },
      {
        id: 'exception-real-meeting-materialized',
        rule_id: 'rule-real-meeting',
        occurrence_date: '2026-07-16',
        action: 'materialized',
        replacement_date: null,
        materialized_id: 'meeting-project',
        created_at: NOW,
        updated_at: NOW,
      },
      {
        id: 'exception-sample-meeting-skip',
        rule_id: 'rule-sample-meeting',
        occurrence_date: '2026-07-13',
        action: 'skip',
        replacement_date: null,
        materialized_id: null,
        created_at: NOW,
        updated_at: NOW,
      },
    ],
    milestones: [
      {
        id: 'milestone-linked',
        project_id: 'project-real',
        linked_task_id: 'task-converted',
        name: '正式发布',
        description: '关联已完成任务',
        date: '2026-07-31',
        status: 'achieved',
        achieved_at: '2026-07-18T08:00:00Z',
        is_sample: 0,
        created_at: NOW,
        updated_at: NOW,
      },
      {
        id: 'milestone-sample',
        project_id: 'project-sample',
        linked_task_id: null,
        name: '示例里程碑',
        description: '',
        date: '2026-08-31',
        status: 'upcoming',
        achieved_at: null,
        is_sample: 1,
        created_at: NOW,
        updated_at: NOW,
      },
    ],
    actionItems: [
      {
        id: 'action-converted',
        meeting_id: 'meeting-project',
        content: '转换为任务',
        owner: 'Racliu',
        due_date: '2026-07-18',
        status: 'done',
        converted_task_id: 'task-converted',
        converted_at: '2026-07-14T09:45:00Z',
        created_at: NOW,
        updated_at: NOW,
      },
      {
        id: 'action-project',
        meeting_id: 'meeting-project',
        content: '继续跟进',
        owner: '项目成员',
        due_date: null,
        status: 'in_progress',
        converted_task_id: null,
        converted_at: null,
        created_at: NOW,
        updated_at: NOW,
      },
      {
        id: 'action-independent-first',
        meeting_id: 'meeting-independent',
        content: '示例行动项一',
        owner: '',
        due_date: null,
        status: 'open',
        converted_task_id: null,
        converted_at: null,
        created_at: NOW,
        updated_at: NOW,
      },
      {
        id: 'action-independent-second',
        meeting_id: 'meeting-independent',
        content: '示例行动项二',
        owner: '',
        due_date: null,
        status: 'cancelled',
        converted_task_id: null,
        converted_at: null,
        created_at: NOW,
        updated_at: NOW,
      },
    ],
    projectLinks: [
      {
        id: 'link-real',
        project_id: 'project-real',
        label: '项目资料',
        link_type: 'url',
        target: 'https://example.com/project',
        description: '',
        is_sample: 0,
        created_at: NOW,
        updated_at: NOW,
      },
      {
        id: 'link-sample',
        project_id: 'project-sample',
        label: '示例资料',
        link_type: 'file_path',
        target: 'C:\\示例\\资料',
        description: '',
        is_sample: 1,
        created_at: NOW,
        updated_at: NOW,
      },
    ],
    risks: [
      {
        id: 'risk-open',
        project_id: 'project-real',
        title: '关键延期',
        description: '需要持续关注',
        category: 'schedule',
        likelihood: 'high',
        impact: 'high',
        level: 'critical',
        status: 'open',
        owner: 'Racliu',
        mitigation_plan: '每日检查',
        due_date: '2026-07-25',
        resolved_at: null,
        is_sample: 0,
        created_at: NOW,
        updated_at: NOW,
      },
      {
        id: 'risk-closed-sample',
        project_id: 'project-sample',
        title: '示例已关闭风险',
        description: '',
        category: 'other',
        likelihood: 'low',
        impact: 'low',
        level: 'low',
        status: 'closed',
        owner: '',
        mitigation_plan: '',
        due_date: null,
        resolved_at: '2026-07-15T00:00:00Z',
        is_sample: 1,
        created_at: NOW,
        updated_at: NOW,
      },
    ],
    appSettings: [
      { key: 'theme', value: 'dark', created_at: NOW, updated_at: NOW },
      { key: 'sample_seeded', value: '1', created_at: NOW, updated_at: NOW },
      { key: 'calendar_week_start', value: 'monday', created_at: NOW, updated_at: NOW },
    ],
    people: [
      {
        id: 'person-owner',
        name: '项目负责人',
        email: 'owner@example.com',
        role: '负责人',
        note: '核心成员',
        created_at: NOW,
        updated_at: NOW,
      },
      {
        id: 'person-member',
        name: '项目成员',
        email: null,
        role: null,
        note: null,
        created_at: NOW,
        updated_at: NOW,
      },
    ],
    projectParticipants: [
      {
        project_id: 'project-real',
        person_id: 'person-owner',
        role: '负责人',
        joined_at: NOW,
      },
      {
        project_id: 'project-sample',
        person_id: 'person-member',
        role: '',
        joined_at: NOW,
      },
    ],
    taskParticipants: [
      { task_id: 'task-root', person_id: 'person-member', assigned_at: NOW },
      { task_id: 'task-sample', person_id: 'person-owner', assigned_at: NOW },
    ],
  };
}

export function cloneSnapshot(snapshot = createCompleteSnapshot()): DatabaseSnapshot {
  return structuredClone(snapshot);
}

export function createTransferHarness(db = createTestDb()) {
  const repository = createDataTransferRepository(db.executor);
  const runBatch = vi.fn((statements: Parameters<TestDb['runBatch']>[0]) =>
    Promise.resolve(db.runBatch(statements)),
  );
  const service = createDataTransferService({ repository, runBatch });
  return { db, repository, runBatch, service };
}

export function seedSnapshot(db: TestDb, snapshot = createCompleteSnapshot()): void {
  const repository = createDataTransferRepository(db.executor);
  db.runBatch(repository.buildInsertStatements(snapshot));
}

export async function createCompleteExport(
  db: TestDb,
  includeSample = true,
): Promise<ProjectPilotExport> {
  const repository = createDataTransferRepository(db.executor);
  const service = createDataTransferService({
    repository,
    runBatch: (statements) => Promise.resolve(db.runBatch(statements)),
  });
  return service.exportData('0.1.0', NOW, includeSample);
}
